### ISSUE TITLE
Laufzeitfehler mit Version 0.9.1 unter Java 1.8

### ISSUE THREAD

**Issue by frankjesgarz** [DAV-ABDA/eRezept-Referenzvalidator#11]
Bei der Ausführung der Version 0.9.1 unter Java 1.8 kommt es zu Laufzeitfehlern, da Sprach-Features genutzt werden, die unter Java 8 nicht zur Verfügung stehen. Offenbar wird in dem Projekt kein Java-Toolchain-Plugin benutzt. Dadurch kommt es zu Laufzeitfehlern, zum Beispiel an folgender Stelle:

`java.lang.NoSuchMethodError: java.util.regex.Matcher.replaceAll(Ljava/util/function/Function;)Ljava/lang/String;
	at de.abda.fhir.validator.core.util.InputHelper.removeVersionInCanonicals(InputHelper.java:17) ~[fhir-validator-core-0.9.1.jar:?]`

Dies scheint das  Gradle-Pendant zum Maven Java-Toolchain-Plugin zu sein: https://docs.gradle.org/current/userguide/toolchains.html

**Comment by murnic** [comment]
Bei der Umstzung der Java8-Unterstützung haben wir den Fehler gemacht, zwar das Language-Level auf 8 zu setzen, jedoch mit einem JDK11 statt JDK1.8 zu testen. Die verbleibenden Fehler kommen daher von fehlenden API-Funktionen. Wir werden schauen, ob wir die fixen können und gehen weiter davon aus, dass die JDK1.8-Kompatibilität im allgemeinen Interesse ist.

**Comment by murnic** [comment]
Mit dem Release der Version 0.9.2 ist nun die Java 8 Unterstüzung gegeben.
