### ISSUE TITLE
Unterstützung der Quittung in Version 1.1.1

### ISSUE THREAD

**Issue by magrimuc** [DAV-ABDA/eRezept-Referenzvalidator#12]
Angehängte Quittung ist in Version ErxReceipt|1.1.1.
Diese wirft mit Validator 0.9.1 Fehler:
`7120 [main] INFO de.abda.fhir.validator.core.Validator - Validator message: ERROR Bundle.entry[3] Entry 'https://erp-ref.zentral.erp.splitdns.ti-dienste.de/Task/160.000.080.746.674.75/PrescriptionDigest' ist nicht durch Traversierung, vom ersten Bundle-Entry ausgehend, erreichbar
7141 [main] INFO de.abda.fhir.cli.ValidatorCLI - Validation result: false -- Error summary: ERROR: 1`

SOLL: eine fertige CLI.jar Datei mit o.g. Version des Quittungsprofils. (Und dann: Validation result: true)

[160.000.080.746.674.75_5rx_quittung_211130115901.xml.txt](https://github.com/DAV-ABDA/eRezept-Referenzvalidator/files/7634036/160.000.080.746.674.75_5rx_quittung_211130115901.xml.txt)

**Comment by ABDA-FHIR** [comment]
Die Quittung stammt aus der RU Version 1.4.0, diese wird vorraussichtlich am 02.12.2021 mit dem Deplayment 1.4.0-1 gefixt und steht so in der Testumgebung der gematik bereit bzw. für den nächsten Konnektathon.

Hier eine gültige Quittung der Version 1.1.1
https://github.com/DAV-ABDA/eRezept-Beispiele/blob/2022-01-01/PZN-Verordnung_Nr_1/PZN_Nr1_ErxReceipt.xml

Hier die korrigierte QuellDatei:
[160.000.080.746.674.75_5rx_quittung_211130115901.xml.korr.txt](https://github.com/DAV-ABDA/eRezept-Referenzvalidator/files/7634887/160.000.080.746.674.75_5rx_quittung_211130115901.xml.korr.txt)
