### ISSUE TITLE
Ta7Sammelrechungsbundle kann nicht validiert werden

### ISSUE THREAD

**Issue by frankjesgarz** [DAV-ABDA/eRezept-Referenzvalidator#13]
Beim Validieren eines Test-Ta7SammelrechnungBundles mit dem Referenzvalidator kommt es zu einer Endlosschleife die letztendlich in einem StackOverflowError während der Erzeugung der Snapshots mündet. Laut Log-Meldungen wurden zirkuläre Abhängigkeiten entdeckt.

[fhir-hapi-test.test.log](https://github.com/DAV-ABDA/eRezept-Referenzvalidator/files/7712135/fhir-hapi-test.test.log)
[stacktrace.txt](https://github.com/DAV-ABDA/eRezept-Referenzvalidator/files/7712136/stacktrace.txt)
[Ta7SammelrechnungBundle_1_0_63593060097519004270.txt](https://github.com/DAV-ABDA/eRezept-Referenzvalidator/files/7712143/Ta7SammelrechnungBundle_1_0_63593060097519004270.txt)

**Comment by magrimuc** [comment]
Der Fehler betrifft Versionen > 0.9.1

**Comment by ABDA-FHIR** [comment]
Fehler (circular dependencies) ab Version 0.9.5 behoben.
