### ISSUE TITLE
removeVersionInCanonicals() braucht > 500 ms statt < 1 ms bei Dateien ohne Zeilenumbrüche

### ISSUE THREAD

**Issue by DarthGizka** [DAV-ABDA/eRezept-Referenzvalidator#3]
Mit "examples-1.0.3/TA7-eAbrechnungsdaten-Maximalbeispiel.xml" aus den GKV-Beispielen ergeben sich folgende Timings für `InputHelper.removeVersionInCanonicals()`:

```
// parser = FhirContext.forR4Cached().newXmlParser()
(1)   2 ms für den originalen Text
(2) 744 ms nach parser.setPrettyPrint(false).encodeResourceToString(resource)
(3)   1 ms nach parser.setPrettyPrint(true).encodeResourceToString(resource)
```

Ursache ist die verwendete Regex:

```
"(https?://.{1,100}(\\..{1,50}){1,10}(/.{1,50}){0,20}/StructureDefinition/.{1,50})(\\|\\d(.\\d+)+)"
```

Aufgrund der Verwendung der Punktklasse in mehreren überflüssigen Untergruppen (noch dazu mit großzügiger Wiederholungserlaubnis) kann die Regex irrsinnige Backtracking-Orgien veranstalten, die - aufgrund der Verwendung der Punktklasse - lediglich durch Zeilenenden gestoppt werden. Wie weit diese Irrfahrten der Regex über das eigentliche Ende des Zieles hinausschießen ist am Unterschied der Zeiten mit und ohne Zeilenumbrüche zu sehen. Mit Zeilenumbrüchen wird die Regex schon wenige Zeichen nach Ende der URL vom Zeilenende gestoppt; ohne Zeilenumbrüche geraten die Ausflüge länger.

Da die Regex blind auf unbekannte Texte losgelassen wird, empfiehlt es sich, ihr weit strengere Zügel anzulegen. Hier ein Beispiel für ein mögliches Herangehen (geteilt zwecks Erkennbarkeit der beiden Capture Groups):

```
"(['\"]https?://[^'\"|]+/StructureDefinition/[^'\"|]*)" +
"\\|[\\w.:+-]*(?:#[^'\"]*)?" +
"(['\"])";
```

Entscheidend ist die Verankerung am Ende über die Anführungszeichen und das Verbieten von diversen Zeichen mit Ankerfunktion in zwischenliegenden Wildcard-Elementen. Laufzeit ist damit ca. 0,2 ms, aber das ist nicht der Punkt. Entscheidend ist, daß die Regex mit dieser Art von Struktur sich besser beherrschen und durchschauen läßt. Großzügige Testbatterien sind aber auch dafür nötig. 

Die o.g. Regex ist lediglich als Beispiel zu sehen und nicht ausgetestet (sie ist nur einmal quer durch meinen FHIR-Package-Cache marschiert). Die FHIR-Spezifikation ist hier leider keine große Hilfe, da sie - soweit ich sehen kann - kaum Einschränkungen bezüglich der Versionsangaben macht. Und im E-Rezept-Umfeld ist man anscheinend ohnehin nicht sonderlich geneigt, sich an die FHIR-Standards zu halten...

Eine Alternative wäre das Hacken der Versionen im Objektmodell, nicht durch blindes Plätten unbekannter Texte. Das würde viel präzisere Kontrolle erlauben, welche Versionen in welchen Canonicals wie gehackt werden (vollständige Beseitigung ist bei weitem nicht die einzige sinnvolle Option hier).

_Die Ehre der Entdeckung gebührt Herrn Faust von AVC Dick, der auch den Workaround (i.e. Pretty-Printing) gefunden hat. Ich habe lediglich die Detektivarbeit geleistet. ;-)_

~~

**P.S.:** mit der neuen Regex habe ich alle Auftreten von versionierten StructureDefinition-URLs aus meinem FHIR-Package-Cache und aus meiner Beispielsammlung einsammeln lassen;  zusätzlich wurden für alle StructureDefinition betreffenden Einträge in allen gefundenen `.index.json` die versionierten Canonicals synthetisiert. Das Ergebnis  (8827 Zeilen) findet sich im Anhang. Dadurch war es möglich `InputHelper.removeVersionInCanonicals()` auf einen größeren Bestand realistischer Beispiele loszulassen, mit bekanntem Sollergebnis.

Erwartungsgemäß scheiterte die Funktion an Canonicals mit nichtnumerischer Prerelease-Angabe ("-rc", "-alpha1"). Weniger erwartet war das Scheitern bei Dingen wie:
```
http://hl7.org/fhir/StructureDefinition/de-ActivityDefinition.participant.modifierExtension|4.0.1
```
Da hat wohl eine überflüssige Begrenzung einer überflüssigen Gruppe zugeschlagen. Insgesamt gab es 388 Aussetzer, alle von einem der beiden genannten Typen. Timings:

```
  20,8 ms zrbj.fhir.uag_glue.VersionUtil.removeVersionFromStructureDefinitionURLs()
 300,9 ms de.abda.fhir.validator.core.util.InputHelper.removeVersionInCanonicals()
```
Bedenklicher ist das Ergebnis, wenn nicht jede URL fein säuberlich in einer eigenen Zeile steht. Nach Wegbügeln der Zeilenenden hat die Funktion nur _ca. jeden 10._ Versionseintrag entfernt (Zeilenumbrüche der Übersichtlichkeit halber hinzugefügt):
```
"http://fhir-registry.smarthealthit.org/StructureDefinition/capabilities|4.0.1"
"http://fhir-registry.smarthealthit.org/StructureDefinition/capabilities|4.6.0"
"http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris|4.0.1"
"http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris|4.6.0"
"http://fhir.abda.de/StructureDefinition/DAV-PR-ERP-AbgabedatenMeta|1.0.0"
"http://fhir.abda.de/StructureDefinition/DAV-PR-ERP-AbgabedatenMeta|1.0.0-rc"
"http://fhir.abda.de/StructureDefinition/DAV-PR-ERP-AbgabedatenMeta|1.0.1"
"http://fhir.abda.de/StructureDefinition/DAV-PR-ERP-AbgabedatenMeta|1.0.2"
"http://fhir.abda.de/StructureDefinition/DAV-PR-ERP-AbgabedatenMeta|1.0.3"
"http://fhir.abda.de/StructureDefinition/DAV-PR-ERP-AbgabedatenMeta|1.1.0"
"http://fhir.abda.de/eRezeptAbgabadaten/StructureDefinition/DAV-PR-ERP-Abgabeinformationen"
```
Mangels definierter Sicherheitsabstände zwischen Canonicals in Ressourcen kann es also durchaus passieren, daß in zu validierenden Ressourcen einige Canonicals ungeschoren davonkommen.

Timings:
```
   15,2 ms zrbj.fhir.uag_glue.VersionUtil.removeVersionFromStructureDefinitionURLs()
19898,9 ms de.abda.fhir.validator.core.util.InputHelper.removeVersionInCanonicals()
```
[versionierte_StructureDefinition_URLs.zip](https://github.com/DAV-ABDA/eRezept-HAPI-Referenzimplementierung/files/7446557/versionierte_StructureDefinition_URLs.zip)

**Comment by ABDA-FHIR** [comment]
WIr haben uns nochmal mit der RegEX beschäftigt und schlagen folgende Variante vor:

['\"](https?:\/\/[^'\"\s|<>]+\/StructureDefinition\/[^'\"\s|<>]+)(\|[^'\"\s|<>]+)['\"]

Diese ist in der Form direkt aus regexr.com kopiert, muss als ggf. für die entsprechende Programmierumgebung angepasst werden. Wir werden diese Variante testweise in den Code übernehmen. Diese Variante erhebt keinen Anspruch darauf, alle möglichen Canonical-Varianten einwandfrei zu identifizieren, sollte jedoch für sämtliche üblichen Vairanten ausreichend sein und die angesprochenen Performance-Probleme durch Nutzung der .-Klasse beheben. Für weitere Verbesserungsvorschläge sind wir natürlich offen.

**Comment by DarthGizka** [comment]
Hier ist eine überarbeitete Version der Regex. Sie ist abgeklopft bezüglich FHIR-Spezifikation, [RFC3986][rfc] (URI-Syntax, einschl. [ABNF][abnf]) und auch im Hinblick auf Performance (ca. 1 ms für 256 KB). Die Deklaration ist direkt aus meinem privaten Incubator-Projekt gelüpft; daher sind die Kommentare noch in Englisch.

```java
/** regex for stripping version suffices (e.g. "|1.2.3-rc") from StructureDefinition URLs in the raw text of JSON or
 * XML resources<br><br>
 *
 * A version suffix gets terminated by whitespace, single or double quotes, angle brackets or '#'. The latter
 * is necessary because FHIR dictates that version suffices be inserted between the URL proper and a possible
 * fragment identifier (see <a href="https://www.hl7.org/fhir/references.html#canonical-fragments">
 * 2.3.0.6 Canonical Reference and Fragments</a>).<br><br>
 *
 * NOTE: the regex was designed exclusively for the purpose of stripping version suffices. It is neither intended
 * nor suited for analysing or matching versioned StructureDefinition URLs (like for determining whether a given
 * property text *is* such a URL or merely *contains* one).
 */
public static final Pattern gSdUrlStripperPattern = Pattern.compile(
    "([Hh][Tt][Tt][Pp][Ss]?://[^|'\"<>\\s#]+/StructureDefinition/[^|'\"<>\\s#]+)" +  // 1st group: the URL
    "(\\|[^'\"<>\\s#]*)",   // 2nd group: the version suffix to be removed
    Pattern.UNICODE_CHARACTER_CLASS );
// * public while in alpha, to allow detailed testing of the production regex
// * contrary to intuition, https? took 50% more time than [Hh][Tt][Tt][Pp][Ss]? even in case-sensitive mode
//   and with CASE_INSENSITIVE the whole regex took three times as long (because of UNICODE_CHARACTER_CLASS)
// * this regex requires the flag UNICODE_CHARACTER_CLASS in order to recognise all the possible kinds of
//   whitespace that may occur between the end of XML element text and the corresponding closing tag
// * Pattern is thread-safe whereas Matcher is not - hence we can only share the Pattern instance
```

Wenn die Tests abgeschlossen sind, dann reiche ich Quelltext und Testressourcen nach.

[rfc]: http://www.ietf.org/rfc/rfc3986.txt
[abnf]: https://www.rfc-editor.org/rfc/rfc3986#appendix-A
[VersionUtil.java.txt](https://github.com/DAV-ABDA/eRezept-Referenzvalidator/files/7554137/VersionUtil.java.txt)

**Comment by ABDA-FHIR** [comment]
Funktion wird nicht mehr genutzt....
