### ISSUE TITLE
Validierungsversuch mit einem beliebigen XML muss zu einer "ungültig" Ausgabe führen und nicht zu einer internen Exception

### ISSUE THREAD

**Issue by bneidhold** [DAV-ABDA/eRezept-Referenzvalidator#30]
[invalid.zip](https://github.com/DAV-ABDA/eRezept-Referenzvalidator/files/7949558/invalid.zip)

Vorschlag: Wenn intern im Validator eine Exception geworfen wird, wird diese zwar gern ausgegeben aber es muss ein gültiges Ergebnis des Validators erzeugt werden -> also ungültig.  Da ist vor allem für den CLI Modus relevant

**Comment by DarthGizka** [comment]
In der Genossenschaft hatten wir das Problem schon durchdiskutiert. An und für sich ist es korrekt, wenn der Validator nur dann ein Urteil abgibt, wenn er es lebend bis zur Ziellinie schafft. 

Es ist zwar fast immer ein Fehler in der zu validierenden Ressource, wenn der Validator vorher abraucht, aber eben nur fast. Es gibt aber keine Garantien, daß das immer so ist.

Bei einigen Exceptions (z.B. aus dem XML- oder JSON-Parser, oder aus dem Validatorkern) ist klar, daß der Fehler in der zu validierenden Ressource liegen muß. Wenn diese gezielt gefangen und in ein Negativergebnis umgewandelt werden, dann läßt sich damit die Inzidenz des Problems reduzieren.
