### ISSUE TITLE
FhirInstanceValidator kennt noch wichtige settings

### ISSUE THREAD

**Issue by disorderedheap** [DAV-ABDA/eRezept-Referenzvalidator#33]
Der FhirInstanceValidator kennt einige Settings, welche im Rahmen der FHIR-Validierung noch relevant erscheinen. Hier mal ein Beispiel zum Setup:

    FhirInstanceValidator instanceValidator = new FhirInstanceValidator(validationSupport);
    instanceValidator.setNoBindingMsgSuppressed( Boolean.parseBoolean( System.getProperty("fhir.noBindingMsgSuppressed", "false")));
    instanceValidator.setNoTerminologyChecks( Boolean.parseBoolean( System.getProperty("fhir.noTerminologyChecks", "false") ));
    instanceValidator.setErrorForUnknownProfiles(Boolean.parseBoolean( System.getProperty("fhir.errorForUnknownProfiles", "true") ));
    instanceValidator.setNoExtensibleWarnings(Boolean.parseBoolean( System.getProperty("fhir.noExtensibleWarnings", "false") ));
    instanceValidator.setAnyExtensionsAllowed(Boolean.parseBoolean( System.getProperty("fhir.anyExtensionsAllowed", "true") ));

Insbesondere dürfte setErrorForUnknownProfiles() das Problem der Warnungen bei unbekannten Profilen angehen. 
Die Defaulteinstellungen sind erstmal intuitiv gewählt und es müsste noch genauer analysiert werden, welches Verhalten damit herauskommt.

**Comment by ABDA-FHIR** [comment]
Vielen Dank, wurde unter https://github.com/DAV-ABDA/eRezept-Referenzvalidator/blob/adb6df6a9836f8aa0353c10ff03cf6b19ec6aac1/core/src/main/java/de/abda/fhir/validator/core/ValidatorFactory.java#L82
berücksichtigt.
