### ISSUE TITLE
de.abda.fhir.validator.core.Validator wirft FEHLER aufgrund falscher Sprach-Locale

### ISSUE THREAD

**Issue by choffmann-scanacs** [DAV-ABDA/eRezept-Referenzvalidator#39]
Hallo zusammen,

Es gilt ja seit der Version 1.0.1 folgende Regel:

`Bitte beachten Sie das die Sprach-Locale, für ein ordnungsgemäßes Validierungsergebnis, ENGLISH sein muss.`

Ich initialisiere den Validator mit folgenden Command-Line-Parametern:

`-Duser.language=en -Duser.country=GB` 

Der FHIR Context des Reference-Validators wird auch korrekt konfiguriert:

![image](https://user-images.githubusercontent.com/56032238/232491006-a0f6ed73-99ca-4f80-86c9-c923d81328c9.png)

Leider sehe ich im Log folgenden Fehler:

`ERROR de.abda.fhir.validator.core.Validator - Sprach-Locale ist nicht wie erwartet ENGLISH! Validierungsergebnis ist unter Umständen nicht korrekt!`

Könntet ihr das mal prüfen? Danke!

**Comment by ABDA-FHIR** [comment]
Vielen Dank für Ihren Hinweis. Wir haben den Fehler erkannt und werden diesen im nächsten Release beheben.
